/**
 * data.js — the Impact Compass Problem Atlas.
 *
 * Curated, structured content on 15 of the world's biggest problems.
 * Editorial rules:
 *  - Every figure is approximate and phrased that way ("roughly", "on the
 *    order of"). Sources are named per problem; treat numbers as context,
 *    not citations. Figures reflect widely-published estimates circa 2024.
 *  - Evidence ratings: 'strong' (multiple RCTs / broad consensus),
 *    'promising' (good but thinner evidence), 'debated' (experts disagree).
 *  - No real charities are named — org types only. Acting is routed through
 *    the AI for Social Impact tools and Givelink.
 */
const COMPASS_CATEGORIES = {
  health:      { name: 'Health',      emoji: '🩺' },
  poverty:     { name: 'Poverty',     emoji: '🌾' },
  environment: { name: 'Environment', emoji: '🌱' },
  society:     { name: 'Society',     emoji: '🫂' },
  animals:     { name: 'Animals',     emoji: '🐾' },
};

const COMPASS_PROBLEMS = [
  {
    id: 'extreme-poverty',
    name: 'Extreme Poverty',
    emoji: '🌍',
    category: 'poverty',
    stat: 'Roughly 800 million people live on less than $3.00 a day',
    trend: { dir: 'improving', text: 'The share of humanity in extreme poverty fell from ~38% in 1990 to under 10% today — one of the great achievements of our era, though progress has slowed since COVID.' },
    understand: {
      scale: 'On the order of 800 million people — about 1 in 10 humans — live below the World Bank extreme poverty line of $3.00/day (2021 prices, adjusted for local costs). Most live in Sub-Saharan Africa and fragile, conflict-affected states.',
      causes: 'Conflict and displacement, weak institutions and infrastructure, limited access to markets, credit, education and healthcare, and climate shocks that wipe out savings held as crops or livestock.',
      sufferers: 'Rural families, children (who are over-represented among the extreme poor), and people in conflict zones. Poverty at this level means chronic hunger, untreated illness, and children working instead of learning.',
      misconception: '"Global poverty keeps getting worse." The opposite: extreme poverty has seen the steepest sustained decline in human history over the last generation. The work is unfinished, not failing.',
    },
    interventions: [
      { name: 'Direct cash transfers', what: 'Giving money directly to the poorest households, unconditionally. Recipients invest in food, roofs, livestock and small businesses.', evidence: 'strong', cost: 'Roughly $1 delivers ~$0.85–0.90 into a family\'s hands; well-studied across dozens of trials.' },
      { name: 'Graduation programs', what: 'A package: a productive asset (like livestock), training, coaching and a small stipend, to help families build a livelihood.', evidence: 'strong', cost: 'Higher cost per household (~$300–2,000+, varying widely by country and package), with benefits persisting years after the program ends.' },
      { name: 'Microfinance', what: 'Small loans to poor entrepreneurs. Popular for decades.', evidence: 'debated', cost: 'RCTs find modest average effects — helpful for some, not transformative at scale; less effective than the hype suggested.' },
    ],
    actions: {
      money: ['Set up a small monthly gift to org types doing direct cash transfers or graduation programs — consistency beats one-offs.', 'Use the "What Would $X Do?" tool to see what a specific amount achieves against poverty.'],
      time: ['Volunteer with local organizations serving low-income families — poverty is global and local.', 'Join or start a giving circle focused on global poverty.'],
      skills: ['Offer professional skills (accounting, software, design) pro-bono to poverty-focused nonprofits via skills-based volunteering platforms.'],
      voice: ['Share the real trend — that extreme poverty is beatable — to counter fatalism.', 'Advocate for development aid and open trade policies with your representatives.'],
    },
    sources: ['World Bank', 'Our World in Data', 'GiveWell'],
  },
  {
    id: 'malaria',
    name: 'Malaria',
    emoji: '🦟',
    category: 'health',
    stat: 'Roughly 600,000 deaths a year — most of them children under five',
    trend: { dir: 'improving', text: 'Malaria death rates roughly halved between 2000 and 2015 thanks to nets and treatment, but progress has plateaued and funding gaps threaten reversals.' },
    understand: {
      scale: 'On the order of 250 million cases and 600,000 deaths a year, ~95% in Sub-Saharan Africa. A child dies of malaria roughly every minute.',
      causes: 'A parasite spread by Anopheles mosquitoes. It persists where health systems are weak, prevention tools are underfunded, and warm climates sustain transmission year-round.',
      sufferers: 'Children under five and pregnant women bear most deaths. Survivors suffer repeated fevers, anemia, lost schooling and lost income — malaria is both a disease of poverty and a cause of it.',
      misconception: '"Malaria is an unsolvable fact of the tropics." It was eliminated from the US and Europe, and dozens of countries have been certified malaria-free in our lifetime. It is beatable — it just isn\'t funded like it.',
    },
    interventions: [
      { name: 'Insecticide-treated bed nets', what: 'Long-lasting nets that protect sleeping families from mosquito bites. One of the most-studied interventions in global health.', evidence: 'strong', cost: 'A net costs a few dollars; distributing them saves a life for on the order of $5,000 (per GiveWell-style analysis).' },
      { name: 'Seasonal malaria chemoprevention', what: 'Giving children preventive antimalarial medicine during the high-transmission season.', evidence: 'strong', cost: 'Roughly $7 per child protected per season; cost-effectiveness comparable to nets.' },
      { name: 'Malaria vaccines (RTS,S and R21)', what: 'The first approved malaria vaccines, now rolling out across Africa.', evidence: 'promising', cost: 'Moderate efficacy (~50–75% against clinical malaria in the first year); a genuine breakthrough whose real-world impact is still accumulating.' },
    ],
    actions: {
      money: ['Fund org types distributing nets or seasonal chemoprevention — among the most cost-effective donations in the world.', 'Try the "What Would $X Do?" tool with malaria to see concrete impact per amount.'],
      time: ['Join fundraising challenges (runs, streams) that channel money to malaria prevention.'],
      skills: ['Data, logistics and translation skills are chronically needed by global-health org types.'],
      voice: ['Malaria is a top candidate when someone asks "where does a donation do the most good?" — say so.', 'Support replenishments of global health funds when they hit the news.'],
    },
    sources: ['WHO', 'Our World in Data', 'GiveWell'],
  },
  {
    id: 'child-mortality',
    name: 'Child Mortality',
    emoji: '👶',
    category: 'health',
    stat: 'Roughly 5 million children under five die each year — most from preventable causes',
    trend: { dir: 'improving', text: 'Under-five deaths fell from ~12.5 million a year in 1990 to ~5 million today. Every year the world sets a new record low — and every year millions of deaths remain preventable.' },
    understand: {
      scale: 'On the order of 13,000 children under five die every day, overwhelmingly in low-income countries. The leading killers — pneumonia, diarrhea, malaria, newborn complications — are all treatable or preventable.',
      causes: 'Poverty, weak health systems, undernutrition (which underlies nearly half of deaths), unsafe water, and gaps in vaccination and skilled birth care.',
      sufferers: 'Newborns in their first month are at highest risk. Families in rural Sub-Saharan Africa and South Asia carry most of the burden.',
      misconception: '"Nothing works in these places." Child mortality has fallen faster than almost any other human-welfare metric — because vaccines, oral rehydration and nets demonstrably work.',
    },
    interventions: [
      { name: 'Childhood vaccination', what: 'Routine immunization against measles, rotavirus, pneumococcus and more.', evidence: 'strong', cost: 'Among the best buys in global health — full immunization costs tens of dollars per child and vaccines are estimated to have saved well over 100 million children since 1974 (WHO).' },
      { name: 'Oral rehydration + zinc', what: 'A simple salt-sugar solution that stops diarrheal dehydration, the classic child killer.', evidence: 'strong', cost: 'Cents per sachet; credited with tens of millions of lives saved since the 1980s.' },
      { name: 'Vitamin A supplementation', what: 'Twice-yearly high-dose capsules for children in deficient regions.', evidence: 'strong', cost: 'Roughly $1–2 per child per year; reduces child mortality meaningfully where deficiency is common.' },
    ],
    actions: {
      money: ['Give to org types running vaccination, nutrition-supplement or maternal-health programs in high-mortality regions.', 'Compare child-health causes in the Charity Comparison Engine.'],
      time: ['Support newborn-supply drives (kits, clothing) via in-kind platforms like Givelink.'],
      skills: ['Medical, midwifery or public-health professionals can do short skilled-volunteer stints with field org types.'],
      voice: ['Champion vaccine confidence in your own community — hesitancy costs children\'s lives everywhere.'],
    },
    sources: ['UNICEF', 'WHO', 'Our World in Data'],
  },
  {
    id: 'hunger',
    name: 'Hunger & Malnutrition',
    emoji: '🍚',
    category: 'poverty',
    stat: 'Roughly 700 million people are undernourished; undernutrition underlies nearly half of child deaths',
    trend: { dir: 'mixed', text: 'Long-run hunger declined for decades, but conflict, climate shocks and COVID pushed numbers back up since 2019.' },
    understand: {
      scale: 'On the order of 700 million people don\'t get enough calories, and over 2 billion lack key micronutrients ("hidden hunger"). Some 45 million children suffer wasting — dangerously low weight — at any time.',
      causes: 'Poverty and food prices, conflict (the single biggest driver of famine), climate shocks, and food systems that deliver calories but not nutrients to the poorest.',
      sufferers: 'Children under five (stunting affects ~1 in 5 globally, limiting brains and bodies for life), pregnant women, and families in conflict zones like the Horn of Africa.',
      misconception: '"There isn\'t enough food in the world." The world grows more than enough calories for everyone; hunger is about poverty, distribution and conflict — not global scarcity.',
    },
    interventions: [
      { name: 'Therapeutic feeding (RUTF)', what: 'Ready-to-use peanut-paste foods that let mothers treat severe child malnutrition at home.', evidence: 'strong', cost: 'On the order of $100–200 for a full course of treatment (the peanut paste itself is roughly $50); recovery rates above 90% in good programs.' },
      { name: 'Food fortification', what: 'Adding iodine, iron, folic acid or vitamin A to staples like salt and flour.', evidence: 'strong', cost: 'Pennies per person per year; iodization alone prevented cognitive impairment for hundreds of millions.' },
      { name: 'School meal programs', what: 'Free meals at school — nutrition plus attendance in one program.', evidence: 'promising', cost: 'Tens of dollars per child per year; consistently boosts enrollment, with more mixed effects on learning.' },
    ],
    actions: {
      money: ['Fund org types doing therapeutic feeding or fortification — unusually high impact per dollar.', 'Donate surplus non-perishable food through local food banks; use Givelink to find who needs what.'],
      time: ['Volunteer at food banks and community kitchens — hunger exists in every city.'],
      skills: ['Logistics, nutrition and agronomy skills are directly useful to food-security org types.'],
      voice: ['When famine warnings hit the news, early funding saves multiples of lives vs late funding — amplify early appeals.'],
    },
    sources: ['FAO', 'WFP', 'Our World in Data'],
  },
  {
    id: 'unsafe-water',
    name: 'Unsafe Water & Sanitation',
    emoji: '💧',
    category: 'health',
    stat: 'Roughly 2 billion people lack safely managed drinking water',
    trend: { dir: 'improving', text: 'Access keeps expanding decade over decade, but population growth and infrastructure decay mean the last quarter of humanity is the hardest to reach.' },
    understand: {
      scale: 'On the order of 2 billion people drink water contaminated or at risk of contamination; ~3.5 billion lack safely managed sanitation. Diarrheal disease — largely water-borne — kills roughly 1 million people a year, heavily children.',
      causes: 'Missing or broken infrastructure, poverty, weak maintenance systems (a huge share of installed rural water points fall into disrepair), and open defecation where sanitation is absent.',
      sufferers: 'Rural Sub-Saharan Africa and South Asia; women and girls, who do most water hauling and lose hours daily; children, who die of the resulting disease.',
      misconception: '"Digging wells solves it." Hardware without maintenance fails within years — the unglamorous work of chlorination, spare parts and fee systems is where impact lives.',
    },
    interventions: [
      { name: 'Water chlorination', what: 'Dilute chlorine at the point of collection or in supplies — kills the pathogens that kill children.', evidence: 'strong', cost: 'On the order of $1–2 per person per year; recent large studies suggest child mortality reductions rivaling the best health interventions.' },
      { name: 'Community sanitation programs', what: 'Ending open defecation through community-led behavior change plus affordable latrines.', evidence: 'promising', cost: 'Tens of dollars per household; effects strongest when whole communities shift together.' },
      { name: 'Handwashing promotion', what: 'Soap and behavior campaigns.', evidence: 'promising', cost: 'Cheap; real but hard-to-sustain behavior effects.' },
    ],
    actions: {
      money: ['Fund chlorination and safe-water org types — a quietly top-tier use of a donation.', 'See what a monthly gift does via the "What Would $X Do?" tool.'],
      time: ['Join river/beach cleanups locally; water stewardship starts where you live.'],
      skills: ['Engineers and hydrologists: field org types actively seek technical volunteers for system design and maintenance programs.'],
      voice: ['Talk about maintenance, not just wells — better public understanding shifts funding to what lasts.'],
    },
    sources: ['WHO/UNICEF JMP', 'Our World in Data', 'GiveWell'],
  },
  {
    id: 'education',
    name: 'Education Gaps',
    emoji: '📚',
    category: 'society',
    stat: 'Roughly 250 million children and youth are out of school; most in-school children in poor countries can\'t read a simple story by age 10',
    trend: { dir: 'mixed', text: 'Enrollment rose spectacularly for decades — the crisis has shifted from access to learning: being in school without learning to read.' },
    understand: {
      scale: 'On the order of 250 million school-age children are out of school, and "learning poverty" — unable to read a simple text by 10 — affects most children in low-income countries even when enrolled.',
      causes: 'Poverty and child labor, conflict and displacement, gender barriers, under-trained and absent teachers, and curricula that outpace where children actually are.',
      sufferers: 'Girls in some regions, children with disabilities, refugees (over half of refugee children are out of school), and rural poor children everywhere.',
      misconception: '"Building schools is the bottleneck." Buildings and enrollment mostly happened; the hard problem now is what children learn inside them.',
    },
    interventions: [
      { name: 'Teaching at the right level', what: 'Grouping children by learning level, not age, for part of the day — pioneered in India, replicated widely.', evidence: 'strong', cost: 'A few dollars per child per year in some formats; among the best-evidenced learning gains in development economics.' },
      { name: 'Structured pedagogy', what: 'Scripted lesson plans, teacher coaching and learner materials as a package.', evidence: 'strong', cost: 'Moderate; consistently improves literacy and numeracy across many countries.' },
      { name: 'One-to-one technology (laptops/tablets)', what: 'Device-distribution programs.', evidence: 'debated', cost: 'Expensive per child; evaluations of pure hardware programs mostly find little learning effect without pedagogy attached.' },
    ],
    actions: {
      money: ['Fund org types doing teaching-at-the-right-level or structured literacy programs.', 'Donate books and school supplies via in-kind platforms like Givelink.'],
      time: ['Tutor or mentor a child locally — one hour a week measurably matters.', 'Volunteer with literacy programs at libraries and schools.'],
      skills: ['Teachers and editors can create or translate open learning materials.'],
      voice: ['Push the conversation from enrollment numbers to learning outcomes when education aid is discussed.'],
    },
    sources: ['UNESCO', 'World Bank', 'J-PAL'],
  },
  {
    id: 'loneliness',
    name: 'Loneliness & Mental Health',
    emoji: '💔',
    category: 'society',
    stat: 'Roughly 1 in 4 adults worldwide report feeling very or fairly lonely; depression and anxiety are leading causes of disability',
    trend: { dir: 'worsening', text: 'Reported loneliness and youth mental distress have risen across many countries over the last decade; the WHO now treats social connection as a global health priority.' },
    understand: {
      scale: 'Surveys suggest on the order of a billion people feel seriously lonely, and mental disorders affect roughly 1 in 8 people at any time. Chronic loneliness is associated with health risks comparable to major established risk factors like smoking or obesity (an association, though causality is still being untangled).',
      causes: 'Weakening community institutions, more solo living, migration and urban anonymity, stigma that keeps people from seeking help, and — debated but plausible — the displacement of in-person connection by screens.',
      sufferers: 'Contrary to stereotype, young adults report the highest loneliness rates in many surveys, alongside the elderly, caregivers, migrants and the bereaved. In poor countries, the mental-health treatment gap exceeds 75%.',
      misconception: '"Loneliness is an old-people problem, and mental illness needs psychiatrists to fix." Young people report more loneliness than their grandparents, and trained lay counselors deliver effective therapy at scale.',
    },
    interventions: [
      { name: 'Lay-counselor talk therapy', what: 'Community members trained to deliver structured therapy (like the "Friendship Bench" model) where psychiatrists are scarce.', evidence: 'strong', cost: 'Tens of dollars per person treated; multiple RCTs show large reductions in depression.' },
      { name: 'Social prescribing & group activities', what: 'Health systems referring lonely patients to community groups, volunteering and shared activities.', evidence: 'promising', cost: 'Cheap; evidence base growing but heterogeneous.' },
      { name: 'Befriending & intergenerational programs', what: 'Structured regular visits or calls pairing volunteers with isolated people.', evidence: 'promising', cost: 'Mostly volunteer time; consistent modest benefits for both sides.' },
    ],
    actions: {
      money: ['Fund org types scaling lay-counselor therapy in low-income countries — a neglected, high-leverage corner of global health.'],
      time: ['Become a befriending volunteer for isolated elderly neighbors — Volunteer Match can turn your schedule into a concrete role.', 'Show up regularly to one community group; consistency is the intervention.'],
      skills: ['Active listening is a trainable skill — take a mental-health first aid or crisis-line training.'],
      voice: ['Check on one person today. Normalizing "how are you, really?" is culture change at the smallest scale.', 'Speak openly about your own mental health to chip at stigma.'],
    },
    sources: ['WHO', 'Gallup/Meta State of Social Connections', 'Our World in Data'],
  },
  {
    id: 'homelessness',
    name: 'Homelessness',
    emoji: '🏠',
    category: 'society',
    stat: 'Rough global estimates: ~150 million people homeless; over 1.5 billion in inadequate housing',
    trend: { dir: 'mixed', text: 'Some countries (like Finland) have nearly ended chronic homelessness; others see it rising with housing costs. Outcomes track policy choices closely.' },
    understand: {
      scale: 'Global data is poor — a common rough estimate is 150 million people without homes and 1.5–1.8 billion in insecure or inadequate housing (UN-linked estimates). In rich countries, homelessness concentrates in high-rent cities.',
      causes: 'Housing costs outpacing incomes is the dominant driver in rich countries; poverty, disasters and displacement dominate elsewhere. Mental illness and addiction are more often consequences and aggravators than root causes.',
      sufferers: 'Single adults in chronic street homelessness are most visible, but families, youth aging out of care, and the "hidden homeless" (couch-surfing, cars) are more numerous.',
      misconception: '"People must solve their addiction/illness before they can be housed." Housing First flips this — housing is the stable platform that makes treatment work, and the evidence backs it.',
    },
    interventions: [
      { name: 'Housing First', what: 'Permanent housing without preconditions, plus voluntary support services.', evidence: 'strong', cost: 'Keeps ~80%+ of chronically homeless people stably housed in trials; offsets a large share of its cost through avoided ER, shelter and jail use, approaching cost-neutral for the highest-need group.' },
      { name: 'Rapid rehousing & eviction prevention', what: 'Short-term rent help and legal aid to stop the slide into homelessness.', evidence: 'promising', cost: 'A few thousand dollars per household — far cheaper than the shelter system it prevents.' },
      { name: 'More housing supply', what: 'Zoning reform and building more homes where people want to live.', evidence: 'strong', cost: 'The structural fix: homelessness rates track housing costs more than anything else. Slow, political, decisive.' },
    ],
    actions: {
      money: ['Fund org types doing Housing First or eviction-prevention legal aid.', 'Donate furniture, coats and household goods — exactly what platforms like Givelink route to people moving into housing.'],
      time: ['Serve consistently at a shelter or street-outreach org — the relationship is the value.', 'Use the "What Can I Donate?" tool to match your spare items to org types that need them.'],
      skills: ['Lawyers: eviction-defense pro bono has outsized impact. Builders and designers: supportive-housing projects need you.'],
      voice: ['Show up at local hearings to support new housing and shelters — scarcity is a policy choice, and meetings are where it\'s made.'],
    },
    sources: ['UN-Habitat', 'OECD', 'Housing First RCT literature'],
  },
  {
    id: 'refugees',
    name: 'Refugees & Displacement',
    emoji: '🕊️',
    category: 'society',
    stat: 'Roughly 120 million people are forcibly displaced — the most ever recorded',
    trend: { dir: 'worsening', text: 'Displacement has roughly doubled in a decade, driven by wars in Syria, Ukraine, Sudan and beyond, and increasingly by climate disasters.' },
    understand: {
      scale: 'On the order of 120 million people are displaced by war, persecution and disaster — more than 1 in 70 humans. Most are displaced within their own countries or hosted by neighboring low- and middle-income countries, not rich ones.',
      causes: 'War and persecution above all; climate shocks increasingly act as a multiplier. Displacement lasts: the average refugee situation persists for years, often decades.',
      sufferers: 'Children make up around 40% of the displaced; over half of refugee children are out of school. Host communities — mostly in poorer countries — carry costs rich-country debates rarely acknowledge.',
      misconception: '"Refugees are mostly heading to rich countries and drain their hosts." ~75% are hosted in low- and middle-income countries, and where refugees can legally work, evidence shows they contribute more than they cost over time.',
    },
    interventions: [
      { name: 'Cash assistance', what: 'Direct cash to displaced families instead of in-kind aid, letting them prioritize their own needs.', evidence: 'strong', cost: 'More efficient than shipping goods in most contexts; now a backbone of modern humanitarian response.' },
      { name: 'Right-to-work & inclusion policies', what: 'Letting refugees work legally, enroll children in school, and access services.', evidence: 'strong', cost: 'Costs little; turns dependency into contribution. The highest-leverage "intervention" is policy.' },
      { name: 'Community sponsorship & resettlement', what: 'Groups of citizens sponsoring a refugee family\'s first year.', evidence: 'promising', cost: 'A few thousand dollars plus volunteer time per family; sponsored refugees integrate faster in Canadian-style programs.' },
    ],
    actions: {
      money: ['Fund cash-assistance and refugee-education org types; in sudden crises, cash to experienced responders beats goods.'],
      time: ['Join or form a community sponsorship group — the single most direct way a citizen can change a refugee family\'s trajectory.', 'Volunteer for language practice and job mentoring with newcomers near you.'],
      skills: ['Legal skills for asylum casework; teaching skills for language classes; HR skills for employment mentoring.'],
      voice: ['Humanize the issue with real stories; support right-to-work policies when they\'re debated locally.'],
    },
    sources: ['UNHCR', 'Our World in Data', 'IRC/ODI research'],
  },
  {
    id: 'climate-change',
    name: 'Climate Change',
    emoji: '🌡️',
    category: 'environment',
    stat: 'The planet is roughly 1.3°C warmer than pre-industrial times; emissions must fall steeply this decade',
    trend: { dir: 'mixed', text: 'Emissions are near their peak while clean energy grows exponentially — the race between the two defines the century. Catastrophic worst cases have become less likely; serious damage is already locked in.' },
    understand: {
      scale: 'Every year adds tens of billions of tonnes of CO₂. Consequences — heat waves, floods, crop stress, sea-level rise — fall hardest on the poorest, who emitted least. Warming of ~2.5–3°C this century is the rough current trajectory; every tenth of a degree avoided matters.',
      causes: 'Burning fossil fuels for electricity, transport, industry and heat (~75% of emissions), plus agriculture and deforestation. The deeper cause: clean alternatives were expensive — that has now changed.',
      sufferers: 'Low-lying and tropical countries, subsistence farmers, outdoor workers, the very young and very old in heat waves — and future generations, who inherit whatever we choose now.',
      misconception: '"It\'s mainly about personal virtue — recycling, straws, your footprint." Individual footprints matter far less than system change: energy policy, technology cost curves and finance move gigatonnes; personal purity moves kilograms.',
    },
    interventions: [
      { name: 'Clean energy deployment & innovation', what: 'Solar, wind, storage, grids, electrification — scaling what is now often the cheapest power in history.', evidence: 'strong', cost: 'Cost declines (~90% for solar since 2010) did more for emissions than most policies; supporting deployment and R&D compounds it.' },
      { name: 'Policy & advocacy', what: 'Carbon pricing, clean-energy standards, permitting reform — changing the rules that move whole economies.', evidence: 'promising', cost: 'High leverage, uncertain attribution: a won policy fight can dwarf a lifetime of personal cuts.' },
      { name: 'Carbon offsets (as typically sold)', what: 'Paying to "cancel" your emissions via forest or cookstove projects.', evidence: 'debated', cost: 'Investigations found many popular offsets vastly overstated; treat cheap offsets skeptically — fund real mitigation instead.' },
    ],
    actions: {
      money: ['Fund climate policy/advocacy org types and clean-tech-deployment nonprofits — analysis suggests dollars there beat offsets by a wide margin.'],
      time: ['Join a local climate or clean-energy advocacy group; permitting fights for solar, wind and transmission are won by people showing up.'],
      skills: ['Engineers, financiers, and communicators are the constraint in climate work — consider steering career time, the biggest lever most people have.'],
      voice: ['Vote climate, every level, every time — and say why out loud.', 'Make the biggest personal swaps where they\'re easy (electrify home/car when due) and talk about them; visible adoption drives neighbors\' adoption.'],
    },
    sources: ['IPCC', 'IEA', 'Our World in Data'],
  },
  {
    id: 'air-pollution',
    name: 'Air Pollution',
    emoji: '💨',
    category: 'environment',
    stat: 'Roughly 7–8 million premature deaths a year — more than malaria, HIV and traffic accidents combined',
    trend: { dir: 'mixed', text: 'Rich countries and China have cut particulate pollution substantially; South Asia and household smoke remain severe. This problem is dramatically underfunded relative to its death toll.' },
    understand: {
      scale: 'Fine particles (PM2.5) from vehicles, industry, crop burning and indoor cooking fires cause on the order of 7–8 million early deaths a year (WHO-linked estimates) — heart disease, stroke, lung cancer, child pneumonia. ~99% of humanity breathes air exceeding WHO guidelines.',
      causes: 'Fossil fuel combustion, crop-residue burning, and roughly 2 billion people cooking on smoky solid fuels indoors — making this problem a twin of both climate and poverty.',
      sufferers: 'City dwellers in South Asia (Delhi\'s air can cut years off life expectancy), women and children near indoor cooking fires, and the unborn — pollution affects birth outcomes.',
      misconception: '"Air pollution is an unfortunate nuisance, not a top killer." It kills roughly 10× more people than all wars and murders combined each year, yet receives a sliver of health funding and attention.',
    },
    interventions: [
      { name: 'Emission standards & enforcement', what: 'Vehicle, power-plant and industrial standards — the policies behind every clean-air success story.', evidence: 'strong', cost: 'The US Clean Air Act\'s benefits are estimated at ~30× its costs; China cut PM2.5 ~40% in under a decade by decree.' },
      { name: 'Clean cooking transition', what: 'LPG, electric or improved stoves replacing indoor solid-fuel fires.', evidence: 'promising', cost: 'Tens of dollars per household per year; health effects depend on how completely smoky fuels are displaced.' },
      { name: 'Monitoring & open data', what: 'Cheap sensors and public dashboards that make invisible air visible and create political pressure.', evidence: 'promising', cost: 'Very cheap; repeatedly a trigger for policy action.' },
    ],
    actions: {
      money: ['Fund clean-air advocacy and monitoring org types — among the most neglected causes per death.'],
      time: ['Host or maintain a public air-quality sensor; contribute to open air-data networks.'],
      skills: ['Data scientists and engineers: open air-quality projects run on volunteers like you.'],
      voice: ['Share your city\'s real-time air data; push for school-zone traffic restrictions and clean bus fleets locally.'],
    },
    sources: ['WHO', 'State of Global Air', 'Our World in Data'],
  },
  {
    id: 'gender-inequality',
    name: 'Gender Inequality',
    emoji: '⚖️',
    category: 'society',
    stat: 'Roughly 12 million girls are married as children each year; over 230 million girls and women alive today were cut',
    trend: { dir: 'improving', text: 'Girls\' schooling, women\'s political participation and laws on violence have improved almost everywhere over 30 years — unevenly, with backlashes, and nowhere near done.' },
    understand: {
      scale: 'On the order of 12 million child marriages a year, ~1 in 3 women experiencing physical or sexual violence in their lifetime (WHO), large gaps in pay, property rights and unpaid care work, and in places like Afghanistan, outright exclusion from school and work.',
      causes: 'Norms and law: inheritance and property rules, impunity for violence, unpaid care falling on women, and poverty that makes daughters\' early marriage a coping strategy.',
      sufferers: 'Girls in the poorest rural regions bear the extremes (child marriage, cutting, school exclusion); everywhere, women absorb violence and unpaid work that caps their possibilities.',
      misconception: '"Culture can\'t change, or changes only over centuries." Child marriage in Bangladesh, cutting in parts of East Africa, and girls\' schooling in the Sahel have all shifted measurably within a generation when programs and local movements aligned.',
    },
    interventions: [
      { name: 'Keeping girls in school', what: 'Scholarships, stipends, uniforms and safe transport that remove the costs pushing girls out.', evidence: 'strong', cost: 'Each extra year of girls\' schooling delays marriage, cuts fertility and raises lifetime earnings — among development\'s best-documented compounding effects.' },
      { name: 'Cash + norms programs against child marriage', what: 'Incentives for delaying marriage combined with community dialogue.', evidence: 'promising', cost: 'Tens to hundreds of dollars per girl; several strong trials, effects vary by context.' },
      { name: 'Violence-prevention programs', what: 'Community mobilization models (like SASA!) shifting norms around partner violence.', evidence: 'promising', cost: 'RCTs show meaningful reductions in violence — rare and precious in this space.' },
    ],
    actions: {
      money: ['Fund girls\'-education and violence-prevention org types working where gaps are largest.'],
      time: ['Mentor girls in STEM or leadership programs locally.'],
      skills: ['Offer legal, financial or digital-safety training to women\'s org types.'],
      voice: ['Support the local women\'s movement organizations that research shows drive policy change — visibility and small grants matter.'],
    },
    sources: ['UNICEF', 'WHO', 'World Bank Gender Data'],
  },
  {
    id: 'factory-farming',
    name: 'Factory Farming',
    emoji: '🐄',
    category: 'animals',
    stat: 'Roughly 80+ billion land animals are slaughtered yearly — most raised in intensive confinement',
    trend: { dir: 'worsening', text: 'Global meat demand keeps rising, so animal numbers rise too — while welfare reforms (cage-free, broiler standards) spread through corporate supply chains.' },
    understand: {
      scale: 'On the order of 80 billion land animals (chickens above all) and up to trillions of fish are killed for food each year. Most chickens and pigs live in systems prioritizing cost over any measure of welfare — cages, crowding, painful fast-growth genetics.',
      causes: 'Meat demand growing with incomes, decades of breeding and confinement optimized purely for cost, and the moral distance supply chains create between eaters and animals.',
      sufferers: 'Broiler chickens and egg-laying hens are the vast numerical majority; farmed fish are the frontier of both scale and neglect. Slaughterhouse workers and polluted rural communities are the human collateral.',
      misconception: '"Animal welfare means being vegan or nothing." Corporate welfare campaigns — cage bans, slower-growing breeds — have improved hundreds of millions of lives per year, funded by donors who mostly still eat meat.',
    },
    interventions: [
      { name: 'Corporate welfare campaigns', what: 'Pressuring food companies to commit to cage-free eggs and better broiler standards, then holding them to it.', evidence: 'strong', cost: 'Analyses estimate a dollar can improve multiple animal-years of life — plausibly the most suffering reduced per dollar anywhere in philanthropy.' },
      { name: 'Alternative proteins', what: 'Plant-based and cultivated meat R&D to compete with animal products on taste and price.', evidence: 'promising', cost: 'A technological bet: if it wins on price, it scales without persuading anyone morally.' },
      { name: 'Individual diet advocacy', what: 'Leafleting and campaigns for veganism.', evidence: 'debated', cost: 'Measured conversion effects are small and decay; institutional and corporate levers look far more cost-effective.' },
    ],
    actions: {
      money: ['Fund corporate-campaign and farm-animal-welfare org types — extraordinary suffering-reduction per dollar.'],
      time: ['Volunteer for welfare-commitment tracking campaigns (much of it is remote research and outreach).'],
      skills: ['Food scientists, supply-chain and marketing professionals are precisely who alternative-protein and campaign org types need.'],
      voice: ['Ask your canteen or favorite chains for cage-free and better-chicken commitments — institutional asks beat individual shaming.', 'Eating less chicken specifically spares the most animals per meal changed.'],
    },
    sources: ['FAO', 'Our World in Data', 'Rethink Priorities'],
  },
  {
    id: 'preventable-blindness',
    name: 'Preventable Blindness',
    emoji: '👁️',
    category: 'health',
    stat: 'Roughly 1 billion people have vision impairment that could be prevented or corrected',
    trend: { dir: 'improving', text: 'Trachoma and river blindness are being eliminated country by country; cataract surgery keeps getting cheaper and more available. Aging populations push the other way.' },
    understand: {
      scale: 'On the order of 43 million people are blind and ~1 billion have preventable or uncorrected impairment — over half of it fixable with glasses or a 15-minute cataract surgery. 90% live in low- and middle-income countries.',
      causes: 'Cataracts (the top cause of blindness), uncorrected refractive error (the top cause of impairment — literally the lack of glasses), plus infectious causes like trachoma where water and sanitation are poor.',
      sufferers: 'The rural elderly poor (cataracts), schoolchildren who can\'t see the board (refractive error), and the poorest communities without clean water (trachoma). Blindness pulls a family member out of work to become a caregiver.',
      misconception: '"Blindness is mostly incurable fate." More than half of it is solved by two of medicine\'s most routine fixes: eyeglasses and cataract surgery.',
    },
    interventions: [
      { name: 'Cataract surgery programs', what: 'High-volume, low-cost surgery camps and eye hospitals restoring sight in minutes.', evidence: 'strong', cost: 'Roughly $25–100 per surgery in efficient programs — sight restored for the price of a dinner out.' },
      { name: 'Glasses provision', what: 'School screening and cheap corrective lenses.', evidence: 'strong', cost: 'A few dollars per pair; trials show immediate learning and productivity gains.' },
      { name: 'Trachoma elimination (SAFE strategy)', what: 'Surgery, antibiotics, face-washing, environmental improvement — a package that has eliminated trachoma in 15+ countries.', evidence: 'strong', cost: 'Antibiotic distribution costs well under a dollar per person per round.' },
    ],
    actions: {
      money: ['Fund cataract and glasses org types — few donations produce a more tangible before/after.', 'Compare vision-focused causes in the Charity Comparison Engine.'],
      time: ['Donate old eyeglasses through collection programs; organize a drive via platforms like Givelink.'],
      skills: ['Optometrists and ophthalmologists: high-volume surgical org types run on visiting professionals.'],
      voice: ['Vision is a neglected, unusually solvable cause — recommend it to friends looking for a first cause to support.'],
    },
    sources: ['WHO World Report on Vision', 'IAPB Vision Atlas', 'Lancet Global Health'],
  },
  {
    id: 'pandemic-preparedness',
    name: 'Pandemic Preparedness',
    emoji: '🦠',
    category: 'health',
    stat: 'COVID-19 caused roughly 20–28 million excess deaths; the next pandemic is a matter of when',
    trend: { dir: 'mixed', text: 'COVID proved both how bad pandemics can be and how fast vaccines can now be made. Attention and funding are already fading — the classic panic-neglect cycle.' },
    understand: {
      scale: 'Excess-mortality estimates put COVID\'s true toll on the order of 20–28 million lives plus trillions in damage. Engineered or natural, future pandemics could be worse; experts treat another COVID-scale event this century as more likely than not.',
      causes: 'Spillover from animals (intensive farming and wildlife trade raise the odds), lab accidents as a debated additional risk, dense global travel, and chronic underinvestment between crises.',
      sufferers: 'Everyone — but concentrated among the elderly, health workers, and poor countries last in line for vaccines. Preparedness is one of the purest "protect all of humanity at once" causes.',
      misconception: '"COVID was a once-a-century event, so we\'re off the hook." The drivers of spillover are intensifying, and biology is getting easier to engineer. Preparedness is cheap insurance priced against civilization-scale losses.',
    },
    interventions: [
      { name: 'Early-warning surveillance', what: 'Wastewater monitoring, genomic sequencing networks and outbreak detection that catch sparks before they\'re fires.', evidence: 'promising', cost: 'Modest ongoing costs; days of earlier detection can change an epidemic\'s whole trajectory.' },
      { name: 'Vaccine platform readiness ("100 days")', what: 'Prototype vaccines, mRNA platforms and manufacturing standing ready to compress response to ~100 days.', evidence: 'promising', cost: 'Billions globally — trivially cheap against tens of trillions in pandemic losses.' },
      { name: 'Indoor air quality (far-UVC, ventilation)', what: 'Making shared air safe the way we once made water safe.', evidence: 'promising', cost: 'Building standards for clean air could suppress many pathogens at once; early but compelling science.' },
    ],
    actions: {
      money: ['Fund biosecurity and pandemic-preparedness org types — a top "neglected relative to importance" cause.'],
      time: ['Public-comment periods and local health-board meetings shape preparedness policy; almost no one shows up. Be the one who does.'],
      skills: ['Biologists, epidemiologists, engineers and policy people: this field is talent-constrained — consider steering career hours toward it.'],
      voice: ['Keep pandemic memory alive: support ventilation standards for schools and paid sick leave — quiet policies that blunt the next one.'],
    },
    sources: ['WHO', 'The Economist excess-death model', 'Johns Hopkins CHS'],
  },
  {
    id: 'tuberculosis',
    name: 'Tuberculosis',
    emoji: '🫁',
    category: 'health',
    stat: 'Roughly 1.25 million deaths a year — the world\'s deadliest infectious disease',
    trend: { dir: 'mixed', text: 'Deaths fell for two decades, then COVID disrupted diagnosis and treatment; TB has retaken the title of top infectious killer.' },
    understand: {
      scale: 'On the order of 10 million people fall ill and 1.25 million die from TB each year — more than malaria and HIV combined in most recent years. Roughly a quarter of humanity carries latent infection.',
      causes: 'A bacterium spread through the air, thriving on poverty: crowding, malnutrition, HIV co-infection, and weak health systems. Incomplete treatment breeds drug-resistant strains.',
      sufferers: 'The poorest households in South and Southeast Asia and Africa; prisoners, miners, and people with HIV. It strikes adults in their working years, so one illness can bankrupt a family.',
      misconception: '"TB is a disease of the past." It kills over a million people every year, quietly, in poor places — it is curable with roughly six months of antibiotics costing tens of dollars.',
    },
    interventions: [
      { name: 'Active case finding + treatment support', what: 'Going out to find undiagnosed cases (X-ray vans, contact tracing) and supporting patients through the full drug course.', evidence: 'strong', cost: 'Treatment cures ~85%+ of drug-sensitive cases; finding and treating a case costs on the order of a few hundred dollars and stops onward transmission.' },
      { name: 'New drug-resistant TB regimens', what: 'Shorter, all-oral regimens (like BPaLM) replacing two years of toxic injections with ~6 months of pills.', evidence: 'promising', cost: 'Cure rates jumped to ~90% in trials for drug-resistant TB — a genuine recent breakthrough now scaling.' },
      { name: 'New TB vaccines (M72 and others)', what: 'The first potentially effective adult TB vaccines in a century, now in late-stage trials.', evidence: 'promising', cost: 'If efficacy holds (~50% in phase 2b), modeling suggests millions of lives over coming decades.' },
    ],
    actions: {
      money: ['Fund org types doing active case finding and treatment support in high-burden countries — among the most cost-effective global health work.'],
      time: ['Join advocacy pushes around global TB fund replenishments — funding gaps are the binding constraint.'],
      skills: ['Data and logistics skills power case-finding programs; lab and clinical skills fit field org types.'],
      voice: ['Simply knowing and saying "TB is still the deadliest infection on Earth" fights the neglect that keeps it that way.'],
    },
    sources: ['WHO Global TB Report', 'Our World in Data'],
  },
  {
    id: 'lead-poisoning',
    name: 'Lead Poisoning',
    emoji: '🧪',
    category: 'environment',
    stat: 'Roughly 1 in 3 children worldwide has blood lead levels high enough to harm their development',
    trend: { dir: 'improving', text: 'Leaded petrol was eliminated globally in 2021 — a quiet triumph — but exposure persists through paint, battery recycling, spices and cookware.' },
    understand: {
      scale: 'UNICEF-linked estimates suggest around 800 million children have concerning blood lead levels, almost all in low- and middle-income countries. Lead is also linked to on the order of 1.5 million deaths a year via cardiovascular disease.',
      causes: 'Informal battery recycling, lead paint (still legally sold in many countries), lead-adulterated spices like turmeric, glazed cookware, and old pipes. It persists because exposure is invisible and its victims are poor children.',
      sufferers: 'Young children absorb lead fastest, and the damage — lost IQ, attention and impulse-control problems — is permanent. South Asia carries the heaviest burden.',
      misconception: '"Lead was solved when leaded gasoline was banned." Petrol was only one source; paint, batteries and contaminated food still poison hundreds of millions of children today.',
    },
    interventions: [
      { name: 'Lead paint regulation', what: 'Passing and enforcing bans on lead in paint — many countries still allow it.', evidence: 'strong', cost: 'Advocacy for paint laws is astonishingly cheap per child protected; recent analyses rank it among the best buys in global development.' },
      { name: 'Source remediation (spices, cookware)', what: 'Testing markets and cutting lead adulteration at the source.', evidence: 'promising', cost: 'Bangladesh cut turmeric lead adulteration to near zero in a few years with monitoring and enforcement — a model now being replicated.' },
      { name: 'Formalizing battery recycling', what: 'Moving used-battery recycling from backyard smelters to controlled facilities.', evidence: 'promising', cost: 'Harder and costlier, but informal recycling is among the most intense exposure sources.' },
    ],
    actions: {
      money: ['Fund lead-elimination advocacy org types — a tiny field where single-digit millions move national policies.'],
      time: ['If you live in a high-burden country, community blood-lead screening drives need volunteers.'],
      skills: ['Chemists, public-health and policy professionals: this field is tiny and talent-hungry.'],
      voice: ['Lead is the textbook neglected problem — telling people it still exists is itself high-leverage.'],
    },
    sources: ['UNICEF / Pure Earth', 'WHO', 'Center for Global Development'],
  },
  {
    id: 'maternal-mortality',
    name: 'Maternal Mortality',
    emoji: '🤰',
    category: 'health',
    stat: 'Roughly 260,000–290,000 women die each year from pregnancy and childbirth — almost all preventably',
    trend: { dir: 'improving', text: 'Deaths fell by roughly a third since 2000, but progress has stalled in recent years and reversed in some countries.' },
    understand: {
      scale: 'A woman dies from pregnancy or childbirth roughly every two minutes. About 70% of deaths are in Sub-Saharan Africa, where lifetime risk averages around 1 in 40 — and is worse still in the highest-burden countries — versus 1 in thousands in rich ones.',
      causes: 'Severe bleeding, hypertensive disorders, infection and unsafe abortion — all treatable. The deeper causes: births without skilled attendants, distance to emergency care, child marriage and early pregnancy.',
      sufferers: 'Poor and rural women, adolescent girls, and the babies and older children left behind — a mother\'s death cascades through a family.',
      misconception: '"Childbirth is just inherently dangerous." Rich countries cut maternal deaths by ~99% over a century. Every solution is known; what\'s missing is access.',
    },
    interventions: [
      { name: 'Skilled birth attendance + emergency obstetric care', what: 'Trained midwives at every birth, with transport and referral to facilities that can do transfusions and C-sections.', evidence: 'strong', cost: 'The backbone of every country that has driven deaths down; midwifery scale-up is one of health\'s best-documented investments.' },
      { name: 'Hemorrhage bundles (E-MOTIVE, tranexamic acid)', what: 'Cheap drugs and a simple detect-and-treat protocol for postpartum bleeding, the top killer.', evidence: 'strong', cost: 'A landmark 2023 trial cut severe bleeding by ~60% using a bundle costing a few dollars per birth.' },
      { name: 'Access to family planning', what: 'Contraception so pregnancies are chosen, spaced and safer.', evidence: 'strong', cost: 'Each dollar is estimated to save several in maternal and newborn care while directly cutting deaths.' },
    ],
    actions: {
      money: ['Fund org types training midwives and equipping rural birth facilities.', 'Donate baby and maternity supplies via in-kind platforms like Givelink.'],
      time: ['Volunteer with maternal-health awareness or transport-fund programs if you\'re in or connected to a high-burden region.'],
      skills: ['Midwives, OB/GYNs and anesthetists: field org types run on visiting trainers who multiply local capacity.'],
      voice: ['Support girls\' education and against child marriage — the strongest upstream shields for young mothers.'],
    },
    sources: ['WHO', 'UNFPA', 'The Lancet'],
  },
  {
    id: 'road-deaths',
    name: 'Road Traffic Deaths',
    emoji: '🚗',
    category: 'society',
    stat: 'Roughly 1.2 million deaths a year — the leading killer of people aged 5 to 29',
    trend: { dir: 'mixed', text: 'Deaths per vehicle keep falling, but totals stay stubbornly high as motorization grows; over 90% of deaths are in low- and middle-income countries.' },
    understand: {
      scale: 'On the order of 1.2 million people die on roads each year — more than malaria — with up to 50 million injured. It is the single biggest killer of children over five and young adults, and costs many countries ~3% of GDP.',
      causes: 'Speed, missing helmets and seatbelts, drink-driving, roads designed for vehicle flow rather than human survival, weak enforcement, and older vehicles without modern safety features exported to poorer countries.',
      sufferers: 'Pedestrians, cyclists and motorcyclists — over half of all deaths — especially young men in LMIC cities, and children walking to school.',
      misconception: '"Crashes are accidents — careless individuals." System design predicts deaths far better than driver virtue: countries that engineered safety (speeds, road design, vehicle standards) cut deaths by 50–80% while driving more than ever.',
    },
    interventions: [
      { name: 'Speed management + safe road design', what: 'Lower urban limits, speed bumps, roundabouts, pedestrian crossings and separated lanes.', evidence: 'strong', cost: 'A 5% cut in average speed reduces deaths ~30%; infrastructure fixes at known blackspots are among the highest-return public investments measured.' },
      { name: 'Helmet and seatbelt laws with enforcement', what: 'The classic package: legislation plus visible enforcement plus public campaigns.', evidence: 'strong', cost: 'Motorcycle helmets cut death risk ~40%; these laws have saved hundreds of thousands of lives where enforced.' },
      { name: 'Safer vehicle standards', what: 'Minimum crash-test and electronic-stability standards for all vehicles, including used exports.', evidence: 'strong', cost: 'Cheap per life saved at policy level; the gap between vehicles sold in rich vs poor markets is a solvable scandal.' },
    ],
    actions: {
      money: ['Fund road-safety advocacy org types working on speed laws and infrastructure in LMICs — heavily neglected relative to the death toll.'],
      time: ['Show up for safe-streets advocacy in your own city: crossings, school zones and bike lanes are won at local meetings.'],
      skills: ['Urban planners, engineers and data analysts: blackspot mapping and street redesign is exactly your skill set.'],
      voice: ['Talk about road deaths as a design problem, not fate — the reframing is what unlocked every success story.'],
    },
    sources: ['WHO Global Status Report on Road Safety', 'iRAP', 'Our World in Data'],
  },
  {
    id: 'tobacco',
    name: 'Tobacco',
    emoji: '🚬',
    category: 'health',
    stat: 'Roughly 8 million deaths a year — the world\'s leading preventable cause of death',
    trend: { dir: 'improving', text: 'Smoking rates are falling almost everywhere, but population growth keeps the death toll high and the industry is pivoting hard to poorer countries.' },
    understand: {
      scale: 'On the order of 1.2 billion people smoke; half of long-term users are killed by it. Around 8 million deaths a year, including ~1.3 million non-smokers from second-hand smoke — more than malaria, TB and HIV combined.',
      causes: 'An addictive product aggressively marketed for a century, cheap where taxes are low, with the industry now concentrating marketing in low- and middle-income countries as rich markets shrink.',
      sufferers: 'Increasingly the poor: ~80% of smokers now live in low- and middle-income countries, where a pack costs least and cessation help barely exists. Families lose income to cigarettes and then breadwinners to disease.',
      misconception: '"Smoking is yesterday\'s problem, basically solved." It still kills more people than any infectious disease, and this century\'s projected toll is measured in hundreds of millions of lives if trends hold.',
    },
    interventions: [
      { name: 'Tobacco taxation', what: 'Raising cigarette prices through excise tax — the WHO\'s single most effective "best buy".', evidence: 'strong', cost: 'A 10% price rise cuts consumption ~4–8%, most among the young and poor; taxation has saved millions of lives and raises revenue while doing it.' },
      { name: 'Smoke-free laws, ad bans, plain packaging', what: 'The policy package pioneered by Australia and spread via the WHO treaty.', evidence: 'strong', cost: 'Cheap to enact; each measure independently reduces uptake, and together they denormalize the product.' },
      { name: 'Cessation support', what: 'Quitlines, nicotine replacement, and physician brief advice.', evidence: 'promising', cost: 'Helpful per person but reaches few in poor countries; policy levers dominate at population scale.' },
    ],
    actions: {
      money: ['Fund tobacco-policy advocacy org types working in LMICs — dollar for dollar among the biggest life-savers in public health.'],
      time: ['Support local smoke-free and tax campaigns when they surface; industry lobbying wins when no one shows up on the other side.'],
      skills: ['Economists, lawyers and communicators are the backbone of tax and policy fights.'],
      voice: ['Counter the "solved problem" narrative — the industry depends on rich-world indifference while it recruits its next billion customers.'],
    },
    sources: ['WHO', 'Our World in Data', 'Tobacconomics'],
  },
  {
    id: 'hiv-aids',
    name: 'HIV / AIDS',
    emoji: '🎗️',
    category: 'health',
    stat: 'Roughly 630,000 deaths a year, and about 40 million people living with HIV',
    trend: { dir: 'improving', text: 'Deaths are down roughly 70% from the 2004 peak thanks to antiretroviral therapy — one of medicine\'s great comebacks — but funding cuts now threaten the gains.' },
    understand: {
      scale: 'On the order of 40 million people live with HIV and 1.3 million are newly infected each year. Around 9 million still aren\'t on treatment — which is why roughly 630,000 still die annually from a manageable condition.',
      causes: 'A virus spread through sex, blood and childbirth. What keeps it killing is not biology but access and stigma: people untested, untreated, or afraid to seek either.',
      sufferers: 'Sub-Saharan Africa carries about two-thirds of the burden; adolescent girls and young women face several times the infection risk of their male peers. Key marginalized groups face both the virus and criminalization.',
      misconception: '"HIV is either a death sentence or a solved problem." Neither: a person on treatment has near-normal life expectancy and cannot transmit the virus (undetectable = untransmittable) — yet hundreds of thousands still die yearly purely for lack of access.',
    },
    interventions: [
      { name: 'Antiretroviral therapy at scale', what: 'Daily pills that suppress the virus to undetectable — the person stays healthy and cannot pass it on.', evidence: 'strong', cost: 'Generic first-line treatment costs well under $100 per person-year; treatment-as-prevention is why new infections keep falling.' },
      { name: 'PrEP (pre-exposure prophylaxis)', what: 'A preventive pill or long-acting injection for people at high risk.', evidence: 'strong', cost: 'Reduces sexual transmission risk by ~99% when taken; new twice-yearly injectables may be a turning point for hard-to-reach groups.' },
      { name: 'Preventing mother-to-child transmission', what: 'Testing and treating mothers so babies are born HIV-free.', evidence: 'strong', cost: 'Cheap, near-total protection; vertical transmission has collapsed wherever coverage is high.' },
    ],
    actions: {
      money: ['Fund org types delivering treatment, testing and PrEP in high-burden regions — proven, funding-constrained work.'],
      time: ['Volunteer with local HIV testing and support organizations; stigma dies through contact.'],
      skills: ['Health workers, counselors and supply-chain professionals keep treatment programs running.'],
      voice: ['Spread "undetectable = untransmittable" — accurate knowledge is itself an anti-stigma, anti-transmission tool.'],
    },
    sources: ['UNAIDS', 'WHO', 'Our World in Data'],
  },
  {
    id: 'neglected-tropical-diseases',
    name: 'Neglected Tropical Diseases',
    emoji: '🪱',
    category: 'health',
    stat: 'Over 1 billion people are affected by diseases most people have never heard of',
    trend: { dir: 'improving', text: 'More than 50 countries have eliminated at least one NTD; Guinea worm has gone from 3.5 million cases to a handful. Quiet, spectacular progress.' },
    understand: {
      scale: 'Roughly 1 in 8 humans suffers from at least one neglected tropical disease — river blindness, schistosomiasis, lymphatic filariasis, trachoma, intestinal worms and more. They blind, disfigure, and keep children out of school and adults out of work.',
      causes: 'Parasites and bacteria thriving where water, sanitation and health systems are weakest. "Neglected" is literal: they affect people with no purchasing power, so they attract a sliver of research and funding.',
      sufferers: 'The rural poorest of the poorest countries — the same families, often carrying several NTDs at once, in a cycle where disease deepens poverty and poverty sustains disease.',
      misconception: '"Rare, exotic diseases." They afflict over a billion people — more than almost any famous disease — they\'re just invisible from rich countries because they rarely kill quickly; they disable instead.',
    },
    interventions: [
      { name: 'Mass drug administration', what: 'Community-wide annual doses of safe, donated drugs that treat and prevent several NTDs at once.', evidence: 'strong', cost: 'Often well under $1 per person per year (drugs are donated by manufacturers; the cost is distribution) — among the cheapest health interventions that exist.' },
      { name: 'Disease elimination campaigns', what: 'Surveillance-driven endgames like Guinea worm eradication and trachoma elimination country by country.', evidence: 'strong', cost: 'Eliminations keep landing: dozens of country-disease pairs certified in the last decade.' },
      { name: 'School-based deworming', what: 'Regular deworming pills through schools.', evidence: 'debated', cost: 'Pennies per child and clearly reduces worm burden; long-run education and income effects are argued over — cheap enough that many analysts back it anyway.' },
    ],
    actions: {
      money: ['Fund mass-drug-administration org types — pennies-per-person delivery of donated medicine is philanthropy\'s best arbitrage.'],
      time: ['Awareness is the bottleneck: even one accurate conversation about NTDs is more than most of these diseases ever get.'],
      skills: ['Logistics, mapping and epidemiology skills directly serve distribution campaigns.'],
      voice: ['Name them. "Neglected" persists because nobody says schistosomiasis at dinner parties.'],
    },
    sources: ['WHO', 'GiveWell', 'END Fund'],
  },
  {
    id: 'digital-exclusion',
    name: 'Digital Exclusion',
    emoji: '📶',
    category: 'society',
    stat: 'Roughly 2.6 billion people — a third of humanity — remain offline',
    trend: { dir: 'improving', text: 'Connectivity keeps spreading, but growth has slowed: the remaining offline third is the hardest and least profitable to reach, and gender gaps persist.' },
    understand: {
      scale: 'On the order of 2.6 billion people are offline — not using the internet at all — overwhelmingly in poorer countries and rural areas. Coverage is no longer the main barrier: most of the offline live under a mobile signal they can\'t afford or can\'t use.',
      causes: 'Device and data costs relative to income, low literacy and digital skills, electricity gaps, and social barriers — in South Asia and Africa women are far less likely to be online than men.',
      sufferers: 'Rural, poor, older and female populations — and increasingly, being offline compounds every other disadvantage, as banking, market prices, health information and government services move online.',
      misconception: '"The internet is basically everywhere now." A third of humanity has never been online; assuming universal connectivity quietly designs them out of modern life.',
    },
    interventions: [
      { name: 'Affordability policy & competition', what: 'Spectrum policy, competition and targeted subsidies that push data and device prices down.', evidence: 'strong', cost: 'Where prices fell below ~2% of monthly income, adoption followed; policy moves markets more than charity here.' },
      { name: 'Digital skills training', what: 'Basic-use training, especially for women — the biggest non-price barrier.', evidence: 'promising', cost: 'Low cost per person; effects strongest when paired with a reason to use it (payments, prices, government services).' },
      { name: 'Community networks & public access', what: 'Locally-run connectivity and free public access points where markets won\'t go.', evidence: 'promising', cost: 'Modest per community; sustainability depends on local ownership.' },
    ],
    actions: {
      money: ['Fund digital-inclusion org types doing skills training and community networks in low-connectivity regions.'],
      time: ['Teach one person to use the internet safely — digital literacy transfers one relationship at a time, including in your own neighborhood.'],
      skills: ['Network engineers and localizers: community networks and local-language content are built by volunteers like you.'],
      voice: ['Push for public services to keep offline channels while the gap exists — digital-only design excludes billions.'],
    },
    sources: ['ITU', 'GSMA', 'World Bank'],
  },
  {
    id: 'corruption',
    name: 'Corruption',
    emoji: '🏛️',
    category: 'society',
    stat: 'Bribery alone is estimated at roughly $1 trillion a year; corruption drains several percent of global GDP',
    trend: { dir: 'mixed', text: 'Some countries have cut corruption dramatically within a decade; elsewhere kleptocracy has professionalized. The tools work — where there\'s will to use them.' },
    understand: {
      scale: 'Rough estimates put bribery at ~$1 trillion a year and total costs far higher. Every stolen health budget, padded contract and bribed inspector converts public money into private wealth — the poorest countries lose multiples of the aid they receive.',
      causes: 'Discretion plus impunity: officials who control access to services or contracts, weak courts and audits, secrecy (shell companies, hidden ownership), and social norms where bribes are just "how things work".',
      sufferers: 'The poor pay the largest share of their income in petty bribes and depend most on the public services corruption hollows out. Corruption kills quietly — through collapsed buildings, fake medicine, and vanished school funds.',
      misconception: '"Corruption is culture — some places are just like that." Georgia, Estonia and others cut corruption drastically in years, not generations, by redesigning systems (digitize services, remove discretion, publish everything) rather than preaching virtue.',
    },
    interventions: [
      { name: 'Digitizing government services', what: 'Moving permits, payments and records online, removing the human gatekeeper a bribe would go to.', evidence: 'strong', cost: 'E-government reforms repeatedly show large drops in petty bribery — the design removes the opportunity rather than testing the morals.' },
      { name: 'Transparency: open contracting & ownership registries', what: 'Publishing public contracts and the real owners of companies.', evidence: 'promising', cost: 'Cheap to mandate; effects depend on someone using the data — which is why the next item matters.' },
      { name: 'Investigative journalism', what: 'Funding the reporters who trace the money.', evidence: 'promising', cost: 'A single investigation can claw back or deter sums thousands of times its cost; journalism is the enforcement layer transparency needs.' },
    ],
    actions: {
      money: ['Fund investigative-journalism and anti-corruption org types — tiny budgets, documented trillion-dollar terrain.'],
      time: ['Civic monitoring works: citizen audits of local budgets and procurement have real records of recovering funds.'],
      skills: ['Accountants, lawyers and data analysts are the scarcest resource in following money.'],
      voice: ['Refuse the small stuff where you live, and support whistleblower protections when they\'re on the ballot — impunity is a habit societies break together.'],
    },
    sources: ['Transparency International', 'World Bank', 'UNODC'],
  },
  {
    id: 'ocean-health',
    name: 'Ocean Health',
    emoji: '🌊',
    category: 'environment',
    stat: 'Roughly 8–11 million tonnes of plastic enter the ocean each year; over a third of fish stocks are overfished',
    trend: { dir: 'worsening', text: 'Plastic flows and ocean heat keep rising — but marine protected areas and managed fisheries show recovery is fast wherever we actually protect.' },
    understand: {
      scale: 'The ocean supplies roughly a fifth of the animal protein eaten by over 3 billion people, and absorbs most of the excess heat and a quarter of the CO₂ we emit. Meanwhile it takes on the order of 10 million tonnes of plastic a year, over a third of assessed fish stocks are overfished, and half of coral reefs are already gone or badly degraded.',
      causes: 'Waste systems that leak (a large share of ocean plastic arrives via a relatively small number of rivers), industrial overfishing — much of it subsidized — abandoned fishing gear, warming and acidification from carbon emissions.',
      sufferers: 'Coastal and island communities who eat and earn from the sea first; small-scale fishers outcompeted by industrial fleets; and marine life on a scale that\'s hard to hold in mind.',
      misconception: '"The fix is cleaning up the garbage patch." Cleanup is the least effective end of the pipe: stopping flows — river interception, waste systems, fishing-gear rules — prevents far more per dollar, and roughly half the Great Pacific patch by mass is fishing gear, not straws.',
    },
    interventions: [
      { name: 'Marine protected areas with real enforcement', what: 'No-take zones where ecosystems rebuild.', evidence: 'strong', cost: 'Fish biomass typically rebounds several-fold inside enforced reserves and spills over to surrounding fisheries — protection pays fishers back.' },
      { name: 'Fisheries management reform', what: 'Science-based catch limits, monitoring, and ending subsidies for overcapacity.', evidence: 'strong', cost: 'Stocks recover reliably where management is real (US and others rebuilt dozens of stocks); the WTO subsidies deal is the global lever.' },
      { name: 'Stopping plastic at the source', what: 'Waste-management infrastructure in high-leakage countries and river interception.', evidence: 'promising', cost: 'Far cheaper per tonne prevented than open-ocean cleanup; the global plastics treaty under negotiation could set the rules.' },
    ],
    actions: {
      money: ['Fund org types doing marine protection enforcement and waste infrastructure in high-leakage regions — not just cleanup imagery.'],
      time: ['Join coastal and river cleanups locally — the data collected drives policy as much as the trash removed.'],
      skills: ['Marine scientists, economists and campaigners: fisheries reform is won in policy rooms.'],
      voice: ['Choose and ask for certified-sustainable seafood, and back marine protected areas when they\'re proposed — local support decides them.'],
    },
    sources: ['FAO', 'Our World in Data', 'Ocean Conservancy'],
  },
];

/* Lookup helper used across views */
function compassProblem(id) {
  return COMPASS_PROBLEMS.find(p => p.id === id) || null;
}
